import { useDeepMemo } from '@jujulego/alma-utils';
import { useMemo } from 'react';

import { ApiUrl, ApiUrlBuilder, urlBuilder, URL_DEPS_SYMBOL } from '../utils';

// Hook
/**
 * Returns an url builder for every form of ApiUrl (string or 1-arg function)
 * This shall be used in a component, as it creates a stable builder even for
 * builders generated by the url template tag.
 *
 * @see urlBuilder
 */
export function useApiUrl<A = void>(url: ApiUrl<A>): ApiUrlBuilder<A> {
  const deps = (typeof url === 'function' && url[URL_DEPS_SYMBOL]) || [url];
  const _deps = useDeepMemo(deps);

  // eslint-disable-next-line react-hooks/exhaustive-deps
  return useMemo(() => urlBuilder(url), _deps);
}
